import { ReactQueryProvider } from "@/lib/providers/query-provider";
import "./globals.css";
//import store from "@/state/store/store";
// import { Provider } from "react-redux";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
