import { ReactQueryProvider } from "@/lib/providers/query-provider";
import "./globals.css";
import { AuthProvider } from '../context/auth-context';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
