import "./globals.css";
//import store from "@/state/store/store";
// import { Provider } from "react-redux";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

//TODO-- add in Provider by wrapping around children
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
